server:
  port: 1112
eureka:
  client:
    register-with-eureka: false #客户端定时发送心跳到eureka的集群，用来告诉集群我这个客户端是健康的
    fetch-registry: false #客户端定时从服务端取注册中心的配置
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka,http://127.0.0.1:1112/eureka
  server:
    enable-self-preservation: false #服务端关闭自我保护模式
  instance:
    hostname: eureka-server-2
    prefer-ip-address: true

